// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'box': string;
  'home': string;
  'items': string;
  'main': string;
  'nextButton': string;
  'pagination': string;
  'prevButton': string;
}
declare var cssExports: CssExports;
export = cssExports;
